### ISSUE TITLE
Can't use surge-preview for pull-request

### ISSUE THREAD

**Issue by jeffmaury** [afc163/surge-preview#124]
In order to use surge-preview for pull-request, we have to have 2 workflows:
- one that is bound to pull-request and that will check the PR but not publish to Surge
- another one that is bound to workflow_run thus will be launched when the previous one is completed.

But surge-preview is complaining that it can't find a PR corresponding to the commit id.

Please note that pull_request_target is not an option for us for security reasons

**Comment by tbouffard** [comment]
The `v1` tag currently contain commit about `workflow_run` https://github.com/afc163/surge-preview/pull/76, that may help. It seems to have been tested in https://github.com/antvis/G2Plot/pull/2069

As of today, there is no specific tagged version (1.5.6 is currently not tagged 827e364674e6767e5b306562a57bac4067ee88a4) that includes the commit, so to have the action that has the `workflow_run` commit, the `v1` tag must be used.

![image](https://user-images.githubusercontent.com/27200110/117173063-ad752000-adcc-11eb-8c78-fd72d97792ba.png)
