### ISSUE TITLE
Can't teardown surge-preview for pull-request

### ISSUE THREAD

**Issue by uidoyen** [afc163/surge-preview#198]
Can't teardown preview using pull-request https://github.com/debezium/debezium.github.io/runs/3817363212?check_suite_focus=true

```
Error: The process '/usr/local/bin/npx' failed with exit code 1
Error: Resource not accessible by integration
```

**Comment by uidoyen** [comment]
@tbouffard Thanks for the response. I have used the same `secrets.SURGE_TOKEN` for both actions but since surge-preview was not working with `pull_request` I have used other actions to do this https://github.com/debezium/debezium.github.io/blob/develop/.github/workflows/surge-preview.yml#L35

**Comment by tbouffard** [comment]
@uidoyen #124 has been fixed so it is now possible to use the `surge-preview` action in a workflow triggered by a `workflow_run` event.
This should allow you to replace all your custom workflow steps in https://github.com/debezium/debezium.github.io/blob/develop/.github/workflows/surge-preview.yml#L35
