### ISSUE TITLE
failed deployment does not fail the workflow

### ISSUE THREAD

**Issue by pixelass** [afc163/surge-preview#255]
expected:

A failed surge deployment should also fail the workflow

actual:

A failed surge deployment results in a successful workflow

Example: https://github.com/pixelass/react-js-template/runs/6706296076?check_suite_focus=true

![Screen Shot 2022-06-02 at 12 45 03](https://user-images.githubusercontent.com/1148334/171613193-5ecc4a97-a0c2-4774-a24c-4c6d5a07b7c6.png)

**Comment by omeraplak** [comment]
Hey ,
You can set `failOnError` property to `true`. default is `false`.
https://github.com/afc163/surge-preview#inputs
