### ISSUE TITLE
Question: Where is surge cli installed?

### ISSUE THREAD

**Issue by phthhieu** [afc163/surge-preview#275]
I’m digesting this repo to implement sth similar. This line of code confused me https://github.com/afc163/surge-preview/blob/main/src/main.ts#L135 and I couldn’t figure out where ‘surge’ command line come from?

Could you please share how it works?  Thanks.

**Comment by tbouffard** [comment]
It's here: https://github.com/afc163/surge-preview/blob/main/src/helpers.ts#L18
The actual command is `npx surge`

**Comment by tbouffard** [comment]
`npx` handles the `surge CLI` installation. See https://docs.npmjs.com/cli/v8/commands/npx
> If any requested packages are not present in the local project dependencies, then they are installed to a folder in the npm cache, which is added to the PATH environment variable in the executed process. A prompt is printed (which can be suppressed by providing either --yes or --no).
