### ISSUE TITLE
关于部署的不是 PR 当前分支而是基础分支的问题

### ISSUE THREAD

**Issue by afc163** [afc163/surge-preview#62]
现象见：https://github.com/antvis/antvis.github.io/pull/85#issuecomment-723432266

解决方式见：https://github.com/afc163/surge-preview/pull/59

---

需要挨个去发 PR：

- [x] https://github.com/ant-design/ant-design-pro 🔀 https://github.com/ant-design/ant-design-pro/pull/7588
- [x] https://github.com/ant-design/pro-components 🔀 https://github.com/ant-design/pro-components/commit/fb2245e41d99401ba7c00c71d42a8e2200cf5fe1
- [ ] https://github.com/NG-ZORRO/ng-zorro-antd
- [x] https://github.com/antvis/antvis.github.io 🔀 https://github.com/antvis/antvis.github.io/pull/87
- [x] https://github.com/antvis/gatsby-theme-antv 🔀 https://github.com/antvis/gatsby-theme-antv/pull/251
- [x] https://github.com/antvis/g2 🔀 https://github.com/antvis/G2/pull/3011
- [x] https://github.com/antvis/g6 🔀 https://github.com/antvis/G6/pull/2274
- [x] https://github.com/antvis/x6 🔀 https://github.com/antvis/X6/pull/286
- [x] https://github.com/antvis/g2plot 🔀 https://github.com/antvis/G2Plot/pull/1897
- [x] https://github.com/umijs/dumi 🔀 https://github.com/umijs/dumi/pull/374
- [x] https://github.com/alibaba/hooks 🔀 https://github.com/alibaba/hooks/pull/717
- [x] https://github.com/youzan/vant 🔀 https://github.com/youzan/vant/pull/7539
- [x] https://github.com/didi/cube-ui 🔀 https://github.com/didi/cube-ui/pull/742
- [x] https://github.com/didi/mand-mobile 🔀 https://github.com/didi/mand-mobile/pull/718
- [x] https://github.com/jdf2e/nutui 🔀 https://github.com/jdf2e/nutui/pull/348
- [x] https://github.com/ant-design-colorful/ant-design-colorful 🔀 https://github.com/ant-design-colorful/ant-design-colorful/commit/10665b30244564e5db622db3a69f1b75352aa271

**Comment by xrkffgg** [comment]
pro-components 
我改过了 https://github.com/ant-design/pro-components/commit/fb2245e41d99401ba7c00c71d42a8e2200cf5fe1

**Comment by xrkffgg** [comment]
dumi: https://github.com/umijs/dumi/pull/374

**Comment by xrkffgg** [comment]
还剩一个，我再提醒下去

**Comment by xrkffgg** [comment]
最后一个 终于有反应了。。。

**Comment by afc163** [comment]
先回滚到 pull_request 再找别的办法。

**Comment by xrkffgg** [comment]
用 g2 的办法吗？

**Comment by afc163** [comment]
也有问题，没找到 PR number，要传过去：https://github.com/antvis/G2/runs/1752970333?check_suite_focus=true

**Comment by xrkffgg** [comment]
那我先把这些回滚到 pull_request ？

**Comment by afc163** [comment]
@xrkffgg 都回滚一下吧。

**Comment by xrkffgg** [comment]
### Revert
- [ ] antd-colorful https://github.com/ant-design-colorful/ant-design-colorful/pull/30
- [ ] pro-components https://github.com/ant-design/pro-components/pull/1743
- [ ] antd-pro https://github.com/ant-design/ant-design-pro/pull/7996
- [ ] antvis.github.io https://github.com/antvis/antvis.github.io/pull/118

**Comment by afc163** [comment]
PR 内容里提醒一下是安全原因。
